### PR TITLE
Add template for CIS 194 homework 01

### PR DESCRIPTION
**Pull request by CristhianMotoche**
@jpvillaisaza I added the template for CIS 194 homework 01, based on the other templates for the homework 10, 11 and 12. I'll try to add more templates later, but could you take a look at this one please?
This could be helpful for the people that is learning Haskell.

### CODE REVIEW

**Comment by jpvillaisaza** [comment]
@CristhianMotoche Awesome, thank you very much. Feel free to merge if it's ready.

**Comment by CristhianMotoche** [comment]
Thanks, but I don't have privileges in this repository.

**Comment by jpvillaisaza** [comment]
@CristhianMotoche You do now.

**Comment by CristhianMotoche** [comment]
Thanks.

**Pull request merged**
